### ISSUE TITLE
don't copy non markdown after generating pages

### ISSUE THREAD

**Issue by ruedigerp** [contentninjaservices/contentninja#4]
Other files that do not have as .markdown or .md extensions are not copied.

**Comment by contentninjaservices** [comment]
commit 258e9715a3b8aadf2a09d7c13978a66af499cbf2
Author: contentninjaservices rpr@9it.de
Date:   Wed Apr 15 03:42:09 2015 +0200

```
fix issue #4 missing non markdown files
```

**Comment by contentninjaservices** [comment]
Test with http://f425c.saas.contentninja.services/gallery/ ok
