### ISSUE TITLE
Add thumbnail filename to gallery 

### ISSUE THREAD

**Issue by ruedigerp** [contentninjaservices/contentninja#8]
example:

{% gallery %}
image.jpg|image_th.png: title
{% endgallery %}

**Comment by contentninjaservices** [comment]
added in branch 0.8.6 

usage:
image.jpg|image_th.png: title
and
image.jpg: title

**Comment by ruedigerp** [comment]
see: https://github.com/contentninjaservices/contentninja/issues/7
